import type { Stage } from '../types';

export const tutorialStages: Stage[] = [
  {
    id: 'stage-01',
    target: '#FFF',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: [],
    par: 2,
  },
  {
    id: 'stage-02',
    target: '#000',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: ['invert'],
    par: 2,
  },
  {
    id: 'stage-03',
    target: '#F0F',
    palette: ['#F00', '#00F'],
    availableOperatorIds: ['add'],
    availableFilterIds: [],
    par: 1,
  },
  {
    id: 'stage-04',
    target: '#FF0',
    palette: ['#F00', '#0F0'],
    availableOperatorIds: ['add'],
    availableFilterIds: [],
    par: 1,
  },
  {
    id: 'stage-05',
    target: '#0FF',
    palette: ['#0F0', '#00F'],
    availableOperatorIds: ['add'],
    availableFilterIds: [],
    par: 1,
  },
  {
    id: 'stage-06',
    target: '#888',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: ['invert'],
    par: 3,
  },
  {
    id: 'stage-07',
    target: '#F80',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: [],
    par: 2,
  },
  {
    id: 'stage-08',
    target: '#0F8',
    palette: ['#0F0', '#00F', '#F00'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: ['invert'],
    par: 2,
  },
  {
    id: 'stage-09',
    target: '#800',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: ['invert'],
    par: 2,
  },
  {
    id: 'stage-10',
    target: '#123',
    palette: ['#F00', '#0F0', '#00F'],
    availableOperatorIds: ['add', 'sub'],
    availableFilterIds: ['invert'],
    par: 3,
  },
  {
    id: 'stage-v1',
    target: '#F08',
    palette: ['#F00'],
    availableOperatorIds: ['add'],
    availableFilterIds: [],
    availableValues: [8],
    par: 1,
  },
];
